<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from "vue";
const props = defineProps({ modelValue: { type: String, default: "" }, min: { type: String, default: "" }, max: { type: String, default: "" } });
const emit = defineEmits(["update:modelValue"]);
const open = ref(false);
const pickerId = `date-picker-${Math.random().toString(36).slice(2)}`;
const normalizedValue = computed(() => String(props.modelValue || "").slice(0, 10));
const today = () => { const d = new Date(); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`; };
const calendarMonth = ref((normalizedValue.value || today()).slice(0, 7));
const monthLabel = computed(() => calendarMonth.value.replace("-", "年") + "月");
const cells = computed(() => { const [y, m] = calendarMonth.value.split("-").map(Number); const start = new Date(y, m - 1, 1).getDay(); const days = new Date(y, m, 0).getDate(); return Array.from({ length: 42 }, (_, i) => { const day = i - start + 1; return day < 1 || day > days ? { key: `empty-${i}`, empty: true } : { key: `${y}-${m}-${day}`, day, date: `${y}-${String(m).padStart(2, "0")}-${String(day).padStart(2, "0")}` }; }); });
const closeWhenAnotherOpens = (event) => { if (event.detail !== pickerId) open.value = false; };
onMounted(() => window.addEventListener("styled-date-picker-open", closeWhenAnotherOpens));
onBeforeUnmount(() => window.removeEventListener("styled-date-picker-open", closeWhenAnotherOpens));
const toggle = () => { calendarMonth.value = (normalizedValue.value || today()).slice(0, 7); open.value = !open.value; if (open.value) window.dispatchEvent(new CustomEvent("styled-date-picker-open", { detail: pickerId })); };
const moveMonth = (amount) => { const [y, m] = calendarMonth.value.split("-").map(Number); const next = new Date(y, m - 1 + amount, 1); calendarMonth.value = `${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, "0")}`; };
const select = (date) => { if ((props.min && date < props.min) || (props.max && date > props.max)) return; emit("update:modelValue", date); open.value = false; };
</script>
<template><div class="relative"><button type="button" class="flex w-full items-center justify-between rounded-lg border border-[#d6cec1] bg-white px-3 py-2 text-left text-sm transition hover:border-[#c96b48] focus:border-[#c96b48] focus:outline-none focus:ring-2 focus:ring-[#f5ded3]" @click="toggle"><span :class="normalizedValue ? 'text-[#3d4b52]' : 'text-[#9f9186]'">{{ normalizedValue ? normalizedValue.replaceAll('-', '/') : '日付を選択' }}</span><svg class="h-4 w-4 text-[#8b7568]" viewBox="0 0 20 20" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><rect x="3.5" y="5" width="13" height="11" rx="1.5" /><path d="M6.5 3v4M13.5 3v4M3.5 8.5h13" /></svg></button><div v-if="open" class="absolute left-0 top-full z-30 mt-1 w-72 rounded-xl border border-[#ded7ca] bg-[#fbf9f4] p-3 text-[#3d4b52] shadow-xl"><div class="flex items-center justify-between"><button type="button" class="rounded-lg p-1.5 hover:bg-[#eee7db]" @click="moveMonth(-1)">‹</button><p class="text-sm font-black">{{ monthLabel }}</p><button type="button" class="rounded-lg p-1.5 hover:bg-[#eee7db]" @click="moveMonth(1)">›</button></div><div class="mt-3 grid grid-cols-7 text-center text-[10px] font-bold text-[#9f9186]"><span v-for="day in ['日', '月', '火', '水', '木', '金', '土']" :key="day" class="py-1">{{ day }}</span></div><div class="grid grid-cols-7 gap-y-0.5 text-center text-xs"><template v-for="cell in cells" :key="cell.key"><span v-if="cell.empty" class="h-8"></span><button v-else type="button" class="h-8 rounded-lg font-semibold transition hover:bg-[#f9ede7] hover:text-[#b65b3d]" :class="normalizedValue === cell.date ? 'bg-[#b65b3d] text-white hover:bg-[#b65b3d] hover:text-white' : ''" @click="select(cell.date)">{{ cell.day }}</button></template></div><div class="mt-3 flex items-center justify-between border-t border-[#e6dfd3] pt-2 text-xs font-bold"><button type="button" class="text-[#b65b3d]" @click="select(today())">今日</button><button type="button" class="text-[#8b7568]" @click="select('')">クリア</button></div></div></div></template>
