<script setup>
import { Link, useForm } from "@inertiajs/vue3";
import StyledDatePicker from "@/Components/StyledDatePicker.vue";
import EnglishBooksLayout from "@/Layouts/EnglishBooksLayout.vue";
const props = defineProps({ book: { type: Object, required: true } });
const dateOnly = (value) => String(value || "").slice(0, 10);
const form = useForm({ status: props.book.status || "want", started_on: dateOnly(props.book.started_on), finished_on: dateOnly(props.book.finished_on), rating: props.book.rating || null, memo: props.book.memo || "" });
const save = () => { if (form.started_on && form.finished_on && form.finished_on < form.started_on) { form.setError("finished_on", "読了日は読み始めた日以降にしてください。"); return; } form.post(route("admin.englishBooks.update", props.book.id)); };
</script>
<template><EnglishBooksLayout :title="`読書記録を編集 — ${book.title}`"><div class="mx-auto max-w-2xl px-4 py-8 pb-16 sm:px-8 sm:py-14 sm:pb-20"><Link :href="route('admin.englishBooks.index')" class="text-sm font-bold text-[#74665e] hover:text-[#c96b48]">← 本棚に戻る</Link><section class="mt-8 rounded-2xl border border-[#ded7ca] bg-[#fbf9f4] p-5 shadow-[0_8px_30px_rgba(72,55,40,0.06)] sm:p-8"><p class="text-xs font-bold tracking-[0.18em] text-[#c96b48]">わたしの読書記録</p><h1 class="mt-2 break-words font-serif text-3xl font-bold text-[#25323a]">{{ book.title }}</h1><p class="mt-2 text-sm text-[#74665e]">読書状況や日付を更新できます。</p><form class="mt-8 grid gap-5 sm:grid-cols-2" @submit.prevent="save"><label><span class="text-sm font-bold text-[#3d4b52]">読書状況</span><select v-model="form.status" class="mt-1.5 block w-full rounded-lg border-[#d6cec1] bg-white text-sm"><option value="want">読みたい</option><option value="reading">読書中</option><option value="finished">読了</option></select></label><label><span class="text-sm font-bold text-[#3d4b52]">評価（1〜5）</span><select v-model="form.rating" class="mt-1.5 block w-full rounded-lg border-[#d6cec1] bg-white text-sm"><option :value="null">未設定</option><option v-for="n in 5" :key="n" :value="n">★ {{ n }}</option></select></label><label><span class="text-sm font-bold text-[#3d4b52]">読み始めた日</span><StyledDatePicker v-model="form.started_on" :max="form.finished_on" class="mt-1.5" /></label><label><span class="text-sm font-bold text-[#3d4b52]">読了日</span><StyledDatePicker v-model="form.finished_on" :min="form.started_on" class="mt-1.5" /><span v-if="form.errors.finished_on" class="mt-1 text-xs text-rose-600">{{ form.errors.finished_on }}</span></label><label class="sm:col-span-2"><span class="text-sm font-bold text-[#3d4b52]">メモ</span><textarea v-model="form.memo" rows="5" class="mt-1.5 block w-full rounded-lg border-[#d6cec1] bg-white text-sm" placeholder="感想、気になった表現など"></textarea></label><div class="sm:col-span-2"><button type="submit" :disabled="form.processing" class="w-full rounded-full bg-[#c96b48] px-7 py-3 text-sm font-bold text-white hover:bg-[#ad5637] disabled:opacity-50 sm:w-auto">読書記録を更新</button></div></form></section></div></EnglishBooksLayout></template>
