<script setup>
import { Link, useForm } from "@inertiajs/vue3";
import EnglishBooksLayout from "@/Layouts/EnglishBooksLayout.vue";

const props = defineProps({ book: { type: Object, required: true } });
const form = useForm({ status: props.book.status || "want", started_on: props.book.started_on || "", finished_on: props.book.finished_on || "", rating: props.book.rating || null, memo: props.book.memo || "" });
const save = () => form.post(route("admin.englishBooks.update", props.book.id));
</script>

<template><EnglishBooksLayout :title="`読書記録を編集 — ${book.title}`"><div class="mx-auto max-w-2xl px-4 py-8 pb-16 sm:px-8 sm:py-14 sm:pb-20"><Link :href="route('admin.englishBooks.show', book.id)" class="text-sm font-bold text-[#74665e] hover:text-[#c96b48]">← 詳細に戻る</Link><section class="mt-8 rounded-2xl border border-[#ded7ca] bg-[#fbf9f4] p-5 shadow-[0_8px_30px_rgba(72,55,40,0.06)] sm:p-8"><p class="text-xs font-bold tracking-[0.18em] text-[#c96b48]">わたしの読書記録</p><h1 class="mt-2 break-words font-serif text-3xl font-bold text-[#25323a]">{{ book.title }}</h1><p class="mt-2 text-sm text-[#74665e]">本の情報ではなく、あなたの読書記録を編集します。</p><form class="mt-8 grid gap-5 sm:grid-cols-2" @submit.prevent="save"><label><span class="text-sm font-bold text-[#3d4b52]">読書状況</span><select v-model="form.status" class="mt-1.5 block w-full rounded-lg border-[#d6cec1] bg-white text-sm"><option value="want">読みたい</option><option value="reading">読書中</option><option value="finished">読了</option></select></label><label><span class="text-sm font-bold text-[#3d4b52]">評価（1〜5）</span><select v-model="form.rating" class="mt-1.5 block w-full rounded-lg border-[#d6cec1] bg-white text-sm"><option :value="null">未設定</option><option v-for="n in 5" :key="n" :value="n">★ {{ n }}</option></select></label><label><span class="text-sm font-bold text-[#3d4b52]">読み始めた日</span><input v-model="form.started_on" type="date" class="mt-1.5 block w-full rounded-lg border-[#d6cec1] bg-white text-sm" /></label><label><span class="text-sm font-bold text-[#3d4b52]">読了日</span><input v-model="form.finished_on" type="date" class="mt-1.5 block w-full rounded-lg border-[#d6cec1] bg-white text-sm" /></label><label class="sm:col-span-2"><span class="text-sm font-bold text-[#3d4b52]">メモ</span><textarea v-model="form.memo" rows="5" class="mt-1.5 block w-full rounded-lg border-[#d6cec1] bg-white text-sm" placeholder="感想、気になった表現など"></textarea></label><div class="sm:col-span-2"><button type="submit" :disabled="form.processing" class="w-full rounded-full bg-[#c96b48] px-7 py-3 text-sm font-bold text-white hover:bg-[#ad5637] disabled:opacity-50 sm:w-auto">読書記録を更新</button></div></form></section></div></EnglishBooksLayout></template>
